package com.example.data.remote

import com.example.data.local.TaskEntity
import com.example.data.local.TaskPriority
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Data model representing structured study productivity recommendations generated by Gemini AI.
 */
data class StudyProductivityReport(
    val summary: String,
    val recommendedSequence: List<RecommendedTaskAction>,
    val focusTechnique: String,
    val totalEstimatedMinutes: Int,
    val breakIntervalMinutes: Int,
    val personalizedProTips: List<String>,
    val rawAdviceMarkdown: String
)

data class RecommendedTaskAction(
    val taskTitle: String,
    val subject: String,
    val priority: String,
    val allocatedMinutes: Int,
    val rationale: String,
    val recommendedTechnique: String
)

/**
 * Service interface for generating AI-powered productivity recommendations from task lists.
 */
interface ProductivityRecommendationService {
    suspend fun getRecommendationsForTasks(
        tasks: List<TaskEntity>,
        availableStudyHours: Double = 3.0,
        energyLevel: String = "Medium", // High, Medium, Low
        studyStyle: String = "Pomodoro (25/5)",
        authToken: String? = null,
        userId: String = "guest_user",
        isGuest: Boolean = (userId == "guest_user")
    ): Result<StudyProductivityReport>
}

/**
 * Implementation of ProductivityRecommendationService utilizing the Gemini API.
 */
class GeminiProductivityRecommendationService(
    private val geminiClient: GeminiClient = GeminiClient
) : ProductivityRecommendationService {

    private val dateFormat = SimpleDateFormat("MMM dd, yyyy", Locale.getDefault())

    override suspend fun getRecommendationsForTasks(
        tasks: List<TaskEntity>,
        availableStudyHours: Double,
        energyLevel: String,
        studyStyle: String,
        authToken: String?,
        userId: String,
        isGuest: Boolean
    ): Result<StudyProductivityReport> {
        if (tasks.isEmpty()) {
            return Result.success(
                StudyProductivityReport(
                    summary = "No pending tasks detected. Add tasks to receive tailored productivity advice!",
                    recommendedSequence = emptyList(),
                    focusTechnique = "Rest & Plan",
                    totalEstimatedMinutes = 0,
                    breakIntervalMinutes = 5,
                    personalizedProTips = listOf("Review upcoming syllabus and maintain a consistent sleep routine."),
                    rawAdviceMarkdown = "🎉 **All caught up!** You have no pending study tasks."
                )
            )
        }

        // Calculate total estimated workload
        val totalMinutes = tasks.sumOf { it.estimatedMinutes }
        val now = System.currentTimeMillis()

        // Format task details for Gemini
        val tasksContext = tasks.mapIndexed { index, task ->
            val dueDays = ((task.dueDate - now) / (1000 * 60 * 60 * 24)).toInt()
            val dueStatus = when {
                dueDays < 0 -> "OVERDUE (${-dueDays} days ago)"
                dueDays == 0 -> "DUE TODAY"
                dueDays == 1 -> "DUE TOMORROW"
                else -> "Due in $dueDays days (${dateFormat.format(Date(task.dueDate))})"
            }
            val priorityEnum = TaskPriority.fromString(task.priority)

            """
            ${index + 1}. Task: "${task.title}"
               - Subject: ${task.subject}
               - Priority: ${priorityEnum.name} (Weight: ${priorityEnum.weight})
               - Category: ${task.category}
               - Estimated Duration: ${task.estimatedMinutes} mins
               - Deadline: $dueStatus
               - Additional Notes: ${task.notes.ifBlank { "None" }}
            """.trimIndent()
        }.joinToString("\n\n")

        val systemInstruction = """
            You are Avora AI, an elite academic advisor and cognitive productivity coach for students and software developers.
            Your mission is to analyze the student's task workload, deadlines, and priorities to generate an actionable, science-backed study schedule that maximizes focus and eliminates procrastination.
            Use Eisenhower Matrix principles, Pomodoro intervals, active recall, and cognitive load balancing.
            Format your response in clean, engaging Markdown with emojis, bold headers, and structured bullet points.
        """.trimIndent()

        val prompt = """
            Here is my current study task list:
            
            $tasksContext
            
            User Context:
            - Available Study Time Today: $availableStudyHours hours (~${(availableStudyHours * 60).toInt()} mins)
            - Current Energy Level: $energyLevel
            - Preferred Study Strategy: $studyStyle
            - Total Task Workload: $totalMinutes minutes
            
            Please provide a comprehensive Productivity Recommendation:
            1. 🎯 **Executive Study Strategy & Daily Objective** (Brief high-impact roadmap)
            2. 📋 **Optimized Execution Sequence (Priority Ranked)**:
               - List each task in exact order of execution with allocated time blocks.
               - Specify WHY it is scheduled in this order (deadline urgency vs cognitive demand).
               - Pair each task with a specific learning technique (e.g., Active Recall, Feynman Technique, Pomodoro Sprint, Spaced Repetition).
            3. ⏱️ **Time-Boxing & Break Schedule**:
               - Structured Pomodoro intervals with mandatory mental recharge breaks.
            4. 💡 **Subject-Specific Mastery Tips**:
               - Practical cognitive advice customized specifically to the subjects listed above.
            5. 🛡️ **Distraction Defense**:
               - Top pitfall to avoid during this specific study block.
        """.trimIndent()

        val geminiResult = geminiClient.getAiResponse(
            prompt = prompt,
            conversationHistory = emptyList(),
            systemInstructionText = systemInstruction,
            taskType = "PRODUCTIVITY_COACH",
            authToken = authToken,
            userId = userId,
            isGuest = isGuest
        )

        return geminiResult.map { markdownReply ->
            parseProductivityReport(
                markdown = markdownReply,
                tasks = tasks,
                totalMinutes = totalMinutes,
                studyStyle = studyStyle
            )
        }
    }

    private fun parseProductivityReport(
        markdown: String,
        tasks: List<TaskEntity>,
        totalMinutes: Int,
        studyStyle: String
    ): StudyProductivityReport {
        // Build sequence from tasks sorted by priority & due date
        val sortedTasks = tasks.sortedWith(
            compareByDescending<TaskEntity> { TaskPriority.fromString(it.priority).weight }
                .thenBy { it.dueDate }
        )

        val recommendedActions = sortedTasks.map { task ->
            val technique = when (task.category.lowercase()) {
                "exam prep" -> "Active Recall & Flashcard Quizzing"
                "project" -> "Deep Work 50m Block (Feynman Breakdown)"
                "homework", "assignment" -> "Pomodoro 25m Sprint"
                "reading" -> "SQ3R Active Summarization"
                else -> "Focused Sprint"
            }
            RecommendedTaskAction(
                taskTitle = task.title,
                subject = task.subject,
                priority = task.priority,
                allocatedMinutes = task.estimatedMinutes,
                rationale = "High impact on upcoming deadlines with optimal cognitive load balancing.",
                recommendedTechnique = technique
            )
        }

        val tips = listOf(
            "Tackle your most demanding task in the first 90 minutes when cognitive energy peaks.",
            "Use 5-minute active recovery breaks (stretch, hydrate) rather than scrolling social media.",
            "Test yourself without notes for 5 minutes after each study block to lock in memory retention."
        )

        val summary = if (tasks.size == 1) {
            "Focused single-objective study sprint for ${tasks.first().subject}."
        } else {
            "Optimized ${tasks.size}-task study plan totaling ${totalMinutes}m of high-leverage focus."
        }

        return StudyProductivityReport(
            summary = summary,
            recommendedSequence = recommendedActions,
            focusTechnique = studyStyle,
            totalEstimatedMinutes = totalMinutes,
            breakIntervalMinutes = if (studyStyle.contains("50")) 10 else 5,
            personalizedProTips = tips,
            rawAdviceMarkdown = markdown
        )
    }
}
